"""create_operator_card

Revision ID: 6b2d63665aee
Revises: aa6de9eaaa03
Create Date: 2026-06-11 18:01:00.929124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b2d63665aee'
down_revision: Union[str, Sequence[str], None] = 'aa6de9eaaa03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'NONACTIVE', name='operatorcardstatus', native_enum=False), nullable=False),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_card_id'), 'operator_card', ['id'], unique=False)
    op.create_index(op.f('ix_operator_card_name'), 'operator_card', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operator_card_name'), table_name='operator_card')
    op.drop_index(op.f('ix_operator_card_id'), table_name='operator_card')
    op.drop_table('operator_card')
    # ### end Alembic commands ###
