"""create_payment_method

Revision ID: bd08ed148261
Revises: e1599ed555c4
Create Date: 2026-06-11 15:34:50.125036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd08ed148261'
down_revision: Union[str, Sequence[str], None] = 'e1599ed555c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('thumbnail', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'NONACTIVE', name='paymentmethodstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_method_code'), 'payment_method', ['code'], unique=False)
    op.create_index(op.f('ix_payment_method_id'), 'payment_method', ['id'], unique=False)
    op.create_index(op.f('ix_payment_method_name'), 'payment_method', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_method_name'), table_name='payment_method')
    op.drop_index(op.f('ix_payment_method_id'), table_name='payment_method')
    op.drop_index(op.f('ix_payment_method_code'), table_name='payment_method')
    op.drop_table('payment_method')
    # ### end Alembic commands ###
