"""create_transaction_type

Revision ID: e945919b2339
Revises: 60004b5fb2a2
Create Date: 2026-06-11 15:15:14.075443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e945919b2339'
down_revision: Union[str, Sequence[str], None] = '60004b5fb2a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('action', sa.Enum('CR', 'DR', name='transactionaction', native_enum=False), nullable=False),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_type_code'), 'transaction_type', ['code'], unique=False)
    op.create_index(op.f('ix_transaction_type_id'), 'transaction_type', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_type_name'), 'transaction_type', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_type_name'), table_name='transaction_type')
    op.drop_index(op.f('ix_transaction_type_id'), table_name='transaction_type')
    op.drop_index(op.f('ix_transaction_type_code'), table_name='transaction_type')
    op.drop_table('transaction_type')
    # ### end Alembic commands ###
